### ISSUE TITLE
Build Flow Plugin

### ISSUE THREAD

**Issue by jareware** [jenkinsci/flowdock-plugin#12]
We had Jenkins successfully deliver notifications to Flowdock, until we switched our job to the Build Flow Plugin (https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin). Now we no longer get notifications, even though the "test connection" button successfully delivers a chat message to our Flowdock flow.

Ideas?

**Comment by anttipitkanen** [comment]
Sorry for the delay in getting back to you! Do you see anything in the build log? The plugin should produce at least some output if it's invoked (success/error)

**Comment by jareware** [comment]
Well I have to say I recently moved away from the Flow Plugin (partly) to get around this issue, so sadly I no longer have an environment in which to reproduce this.

Feel free to close.

**Comment by OsQu** [comment]
Alright I'll close this. Feel free to open if somebody else has the same problem.
